name: Publish package to GitHub Packages

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Get the release version
        id: get_version
        run: echo "RELEASE_VERSION=\${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build package
        run: mvn clean package -Drevision=${{ env.RELEASE_VERSION }}
      - name: Publish package
        run: mvn deploy -Drevision=${{ env.RELEASE_VERSION }} -DskipTests

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
